dist: xenial

matrix:
  include:
    - os: linux
      language: d
      d: "dmd-2.081.2"
      env:
        - ENV="DMD 2.081"
        - PYTHON_VERSION="3.7"
      script:
        - dmd --version
        - red-baron test

before_install:
  - pyenv versions
  - pyenv global ${PYTHON_VERSION}
  - pip install --upgrade pip
  - pip install git+https://github.com/asi1024/red-baron.git

cache:
  - apt
  - pip
  - directories:
    - ${HOME}/.red_baron

sudo: required

notifications:
  email: false
