dist: xenial

matrix:
  include:
    - os: linux
      language: d
      d: "dmd-2.081.2"
      env:
        - ENV="DMD 2.081"
        - PYTHON_VERSION="3.7"
      script:
        - dmd --version
        - red-baron test

    - language: python
      python: '3.7'
      addons:
        apt:
          packages:
            - 'clang-format-3.9'
      env:
        - ENV="Doxygen 1.8.13, ClangFormat"
        - PYTHON_VERSION="3.7"
      install:
        - wget https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz
        - tar xpvf Release_1_8_13.tar.gz
        - pushd doxygen-Release_1_8_13
        - cmake -DCMAKE_INSTALL_PREFIX=/usr .
        - sudo make install
        - popd
      script:
        - doxygen --version
        - python --version
        - ./build.sh
        - git diff --exit-code

before_install:
  - pyenv versions
  - pyenv global ${PYTHON_VERSION}
  - pip install --upgrade pip
  - pip install git+https://github.com/asi1024/red-baron.git

cache:
  - apt
  - pip
  - directories:
    - ${HOME}/.red_baron

sudo: required

notifications:
  email: false
